module.exports = {
	standardDomainName: {
		type: "schemas-upnp-org",
		id: "upnp-org"
	},
	searchIntervalInSeconds: 60,
	defaultDeviceTimeoutInSeconds: 900,
	MatchStickMacAddresses: ['98-3B-16', '02-1A-11'],
	ChromecastMacAddresses: [],
	FireTVStickMacAddresses: [],
	RokuMacAddresses: [],
	SSDPServiceType: 'upnp:rootdevice',//'ssdp:all'
	uuidRegex: /(?:uuid:)([^:]*)/i,
	MulticastIP: '239.255.255.250',
	MulticastPort: 1900,
	PeerNameResolutionProtocolST: 'urn:microsoft windows peer name resolution protocol: v4:ipv6:linklocal',
	MSearch: 'M-SEARCH * HTTP/1.1\r\n' +
	'HOST: {0}:{1}\r\n' +
	'ST: {2}\r\n' +
	'MAN: "ssdp:discover"\r\n' +
	'MX: 2\r\n\r\n',
	ssdp: {
		update: "ssdp:update",
		new: "ssdp:alive",
		gone: "ssdp:byebye"
	},
	SOAP: {
		ContentType: 'text/xml; charset=utf-8',
		Body: '<?xml version="1.0" encoding="utf-8"?>\n' +
        '<SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">' +
		'<SOAP-ENV:Body>' +
		'<m:{1} xmlns:m="{0}">' +
		'{2}' +
		'</m:{1}>' +
		'</SOAP-ENV:Body>' +
        '</SOAP-ENV:Envelope>',
		datatypes: {
			"ui1": "int", //Unsigned 1 Byte int. Same format as int without leading sign.
			"ui2": "int", //Unsigned 2 Byte int. Same format as int without leading sign.
			"ui4": "int", //Unsigned 4 Byte int. Same format as int without leading sign.
			"i1": "int", //1 Byte int. Same format as int.
			"i2": "int", //2 Byte int. Same format as int.
			"i4": "int", //4 Byte int. Same format as int. MUST be between -2147483648 and 2147483647.
			"int": "int", //Fixed point, integer number. MAY have leading sign. MAY have leading zeros, which SHOULD be ignored by the recipient. (No currency symbol.) (No grouping of digits to the left of the decimal, e.g., no commas.)
			"r4": "float", //4 Byte float. Same format as float. MUST be between 3.40282347E+38 to 1.17549435E-38.
			"r8": "float", //8 Byte float. Same format as float. MUST be between -1.79769313486232E308 and 4.94065645841247E-324 for negative values, and between 4.94065645841247E-324 and 1.79769313486232E308 for positive values, i.e., IEEE 64-bit (8-Byte) double.
			"number": "float", //Same as r8.
			"float": "float", //Same as r8 but no more than 14 digits to the left of the decimal point and no more than 4 to the right.
			"fixed.14.4": "float", //Floating point number. Mantissa (left of the decimal) and/or exponent MAY have a leading sign. Mantissa and/or exponent MAY have leading zeros, which SHOULD be ignored by the recipient. Decimal character in mantissa is a period, i.e., whole digits in mantissa separated from fractional digits by period ("."). Mantissa separated from exponent by "E". (No currency symbol.) (No grouping of digits in the mantissa, e.g., no commas.)
			"char": "char", //Unicode string. One character long.
			"string": "string", //Unicode string. No limit on length.
			"date": "date", //Date in a subset of ISO 8601 format without time data.
			"dateTime": "dateTime", //Date in ISO 8601 format with OPTIONAL time but no time zone.
			"dateTime.tz": "dateTimeZone", //Date in ISO 8601 format with OPTIONAL time and OPTIONAL time zone.
			"time": "time", //Time in a subset of ISO 8601 format with no date and no time zone.
			"time.tz": "timeZone", //Time in a subset of ISO 8601 format with OPTIONAL time zone but no date.
			"boolean": "boolean", //"0" for false or "1" for true. The values "true", "yes", "false", or "no" are deprecated and MUST NOT be sent but MUST be accepted when received. When received, the values "true" and "yes" MUST be interpreted as true and the values  "false" and "no" MUST be interpreted as false.
			"bin.base64": "base64", //MIME-style Base64 encoded binary BLOB. Takes 3 Bytes, splits them into 4 parts, and maps each 6 bit piece to an octet. (3 octets are encoded as 4.) No limit on size.
			"bin.hex": "hex", //Hexadecimal digits representing octets. Treats each nibble as a hex digit and encodes as a separate Byte. (1 octet is encoded as 2.) No limit on size.
			"uri": "uri", //Universal Resource Identifier.
			"uuid": "uuid" //Universally Unique ID. See section  1.1.4, "UUID format and RECOMMENDED generation algorithms" for the MANDATORY UUID format.
		}
	},
	PreconditionFailed: 412,
	retryLimit: 3,
	ModelNames: {
		MatchStick: 'MatchStick',
		Chromecast: 'Eureka Dongle',
		Firestick: 'FireTV Stick'
	},
	ServiceTypes: {
		AddressBook: "urn:schemas-upnp-org:service:AddressBook:1",
		AVTransport: 'urn:schemas-upnp-org:service:AVTransport:1',
		AVTransportv2: 'urn:schemas-upnp-org:service:AVTransport:2',
		AVTransportv3: 'urn:schemas-upnp-org:service:AVTransport:3',
		BasicManagement: "urn:schemas-upnp-org:service:BasicManagement:1",
		BasicManagementv2: "urn:schemas-upnp-org:service:BasicManagement:2",
		Calendar: "urn:schemas-upnp-org:service:Calendar:1",
		CallManagement: "urn:schemas-upnp-org:service:CallManagement:1",
		CallManagementv2: "urn:schemas-upnp-org:service:CallManagement:2",
		ConfigurationManagement: "urn:schemas-upnp-org:service:ConfigurationManagement:1",
		ConfigurationManagementv2: "urn:schemas-upnp-org:service:ConfigurationManagement:2",
		ConnectionManager: 'urn:schemas-upnp-org:service:ConnectionManager:1',
		ConnectionManagerv2: 'urn:schemas-upnp-org:service:ConnectionManager:2',
		ConnectionManagerv3: 'urn:schemas-upnp-org:service:ConnectionManager:3',
		ContentDirectory: 'urn:schemas-upnp-org:service:ContentDirectory:1',
		ContentDirectoryv2: 'urn:schemas-upnp-org:service:ContentDirectory:2',
		ContentDirectoryv3: 'urn:schemas-upnp-org:service:ContentDirectory:3',
		ContentDirectoryv4: 'urn:schemas-upnp-org:service:ContentDirectory:4',
		ContentSync: "urn:schemas-upnp-org:service:ContentSync:1",
		Controlvalve: "urn:schemas-upnp-org:service:controlValve:1",
		DataStore: "urn:schemas-upnp-org:service:DataStore:1",
		DeviceProtection: "urn:schemas-upnp-org:service:DeviceProtection:1",
		DeviceSecurity: "urn:schemas-upnp-org:service:DeviceSecurity:1",
		DIALMultiscreen: 'urn:dial-multiscreen-org:service:dial:1',
		DigitalSecurityCameraSettings: "urn:schemas-upnp-org:service:DigitalSecurityCameraSettings:1",
		DigitalSecurityCameraStillImage: "urn:schemas-upnp-org:service:DigitalSecurityCameraStillImage:1",
		DigitalSecurityCameraMotionImage: "urn:schemas-upnp-org:service:DigitalSecurityCameraMotionImage:1",
		Dimming: "urn:schemas-upnp-org:service:DimmingService:1 ",
		EnergyManagement: "urn:schemas-upnp-org:service:EnergyManagement:1",
		ExternalActivity: "urn:schemas-upnp-org:service:ExternalActivity:1",
		FanSpeed: "urn:schemas-upnp-org:service:FanSpeed:1",
		Feeder: "urn:schemas-upnp-org:service:Feeder:1",
		HVACUserOperatingMode: "urn:schemas-upnp-org:service:HVAC_UserOperatingMode:1",
		HVACFanOperatingMode: "urn:schemas-upnp-org:service:HVAC_FanOperatingMode:1",
		HVACSetpointSchedule: "urn:schemas-upnp-org:service:HVAC_SetpointSchedule:1",
		InboundConnectionConfig: "urn:schemas-upnp-org:service:InboundConnectionConfig:1",
		InputConfig: "urn:schemas-upnp-org:service:InputConfig:1",
		IRCC: 'urn:schemas-sony-com:service:IRCC:1',
		LinkAuthentication: "urn:schemas-upnp-org:service:LinkAuthentication:1",
		Layer3Forwarding: 'urn:schemas-upnp-org:service:Layer3Forwarding:1',
		LowPower: "urn:schemas-upnp-org:service:LowerPowerDevice:1",
		MediaManagement: "urn:schemas-upnp-org:service:MediaManagement:1",
		MediaManagementv2: "urn:schemas-upnp-org:service:MediaManagement:2",
		MediaReceiverRegistrar: 'urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1',
		Messaging: "urn:schemas-upnp-org:service:Messaging:1",
		Messagingv2: "urn:schemas-upnp-org:service:Messaging:2",
		MicrosoftWindowsPeerNameResolutionProtocol: 'urn:Microsoft Windows Peer Name Resolution Protocol:v4:IPV6:LinkLocal',
		Party: 'urn:schemas-sony-com:service:Party:1',
		Presence: "urn:schemas-upnp-org:service:Presence:1",
		PrintBasic: "urn:schemas-upnp-org:service:PrintBasic:1",
		PrintEnhancedLayout: "urn:schemas-upnp-org:service:PrintEnhancedLayout:1",
		QoSDevice: "urn:schemas-upnp-org:service:QosDevice:1",
		QoSDevicev2: "urn:schemas-upnp-org:service:QosDevice:2",
		QoSDevicev3: "urn:schemas-upnp-org:service:QosDevice:3",
		QoSManager: "urn:schemas-upnp-org:service:QosManager:1",
		QoSManagerv2: "urn:schemas-upnp-org:service:QosManager:2",
		QoSManagerv3: "urn:schemas-upnp-org:service:QosManager:3",
		QoSPolicyHolder: "urn:schemas-upnp-org:service:QosPolicyHolder:1",
		QoSPolicyHolderv2: "urn:schemas-upnp-org:service:QosPolicyHolder:2",
		QoSPolicyHolderv3: "urn:schemas-upnp-org:service:QosPolicyHolder:3",
		RadiusClient: "urn:schemas-upnp-org:service:RadiusClient:1",
		RemoteAccessDiscoveryAgentSync: "urn:schemas-upnp-org:service:RADASync:1",
		RemoteAccessDiscoveryAgentSyncv2: "urn:schemas-upnp-org:service:RADASync:2",
		RemoteAccessDiscoveryAgentConfig: "urn:schemas-upnp-org:service:RADAConfig:1",
		RemoteAccessDiscoveryAgentConfigv2: "urn:schemas-upnp-org:service:RADAConfig:2",
		RemoteAccessTransportAgentConfig: "urn:schemas-upnp-org:service:RATAConfig:1",
		RemoteUIClient: "urn:schemas-upnp-org:service:RemoteUIClient:1",
		RemoteUIServer: "urn:schemas-upnp-org:service:RemoteUIServer:1",
		RenderingControl: 'urn:schemas-upnp-org:service:RenderingControl:1',
		SamsungMultiscreen: "urn:samsung.com:service:MultiScreenService:1",
		Scan: "urn:schemas-upnp-org:service:Scan:1",
		ScheduledRecording: "urn:schemas-upnp-org:service:ScheduledRecording:1",
		ScheduledRecordingv2: "urn:schemas-upnp-org:service:ScheduledRecording:2",
		SecurityConsole: "urn:schemas-upnp-org:service:SecurityConsole:1",
		SensorTransportGeneic: "urn:schemas-upnp-org:service:SensorTransportGeneric:1",
		SoftwareManagement: "urn:schemas-upnp-org:service:SoftwareManagement:1",
		SoftwareManagementv2: "urn:schemas-upnp-org:service:SoftwareManagement:2",
		SwitchPower: "urn:schemas-upnp-org:service:SwitchPower:1 ",
		TemperatureSensor: "urn:schemas-upnp-org:service:TemperatureSensor:1",
		TemperatureSetpoint: "urn:schmeas-upnp-org:service:TemperatureSetpoint:1",
		TwoWayMotionMotor: "urn:schemas-upnp-org:service:TwoWayMotionMotor:1",
		WANCommonInterfaceConfig: 'urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1',
		WANIPConnection: 'urn:schemas-upnp-org:service:WANIPConnection:1',
		WANPPPConnection: 'urn:schemas-upnp-org:service:WANPPPConnection:1',
		WLANConfiguration: "urn:schemas-upnp-org:service:WLANConfiguration:1",
		WFAWLANConfig: 'urn:schemas-wifialliance-org:service:WFAWLANConfig:1',
		XCIS: 'urn:schemas-sony-com:service:X_CIS:1'
	},
	DeviceTypes: {
		Basic: "urn:schemas-upnp-org:device:Basic:1",
		BinaryLight: "urn:schemas-upnp-org:device:BinaryLight:1",
		DIALMultiscreen: 'urn:dial-multiscreen-org:device:dial:1',
		DigitalSecurityCamera: "urn:schemas-upnp-org:device:DigitalSecurityCamera:1",
		HVAC: "urn:schemas-upnp-org:device:HVAC_System:1",
		HVACZoneThermostat: "urn:schemas-upnp-org:device:HVAC_ZoneThermostat:1",
		InternetGateway: "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
		InternetGatewayv2: "urn:schemas-upnp-org:device:InternetGatewayDevice:2",
		Light: "urn:schemas-upnp-org:device:Light:1",
		ManageableDevice: "urn:schemas-upnp-org:device:ManageableDevice:1",
		ManageableDevicev2: "urn:schemas-upnp-org:device:ManageableDevice:2",
		MediaRenderer: "urn:schemas-upnp-org:device:MediaRenderer:1",
		MediaRendererv2: "urn:schemas-upnp-org:device:MediaRenderer:2",
		MediaRendererv3: "urn:schemas-upnp-org:device:MediaRenderer:3",
		MediaServer: "urn:schemas-upnp-org:device:MediaServer:1",
		MediaServerv2: "urn:schemas-upnp-org:device:MediaServer:2",
		MediaServerv3: "urn:schemas-upnp-org:device:MediaServer:3",
		MediaServerv4: "urn:schemas-upnp-org:device:MediaServer:4",
		Printer: "urn:schemas-upnp-org:device:printer:1",
		RemoteAccessClient: "urn:schemas-upnp-org:device:RAClient:1",
		RemoteAccessDiscoveryAgent: "urn:schemas-upnp-org:device:RADiscoveryAgent:2",
		RemoteAccessServer: "urn:schemas-upnp-org:device:RAServer:1",
		RemoteAccessServerv2: "urn:schemas-upnp-org:device:RAServer:2",
		RemoteUIClient: "urn:schemas-upnp-org:device:RemoteUIClientDevice:1",
		RemoteUIServer: "urn:schemas-upnp-org:device:RemoteUIServerDevice:1",
		Root: 'upnp:rootdevice',
		Scanner: "urn:schemas-upnp-org:device:Scanner:1",
		SensorManagement: "urn:schemas-upnp-org:device:SensorManagement:1",
		SolarProtectionBlind: "urn:schemas-upnp-org:device:SolarProtectionBlind:1",
		TelephonyClient: "urn:schemas-upnp-org:device:TelephonyClient:1",
		TelephonyClientv2: "urn:schemas-upnp-org:device:TelephonyClient:2",
		TelephonyServer: "urn:schemas-upnp-org:device:TelephonyServer:1",
		TelephonyServerv2: "urn:schemas-upnp-org:device:TelephonyServer:2",
		WAN: 'urn:schemas-upnp-org:device:WANDevice:1',
		WANConnection: 'urn:schemas-upnp-org:device:WANConnectionDevice:1',
		WLANAccessPoint: "urn:schemas-upnp-org:device:WLANAccessPointDevice:1",
		WFA: 'urn:schemas-wifialliance-org:device:WFADevice:1'
	},
	IconDefaults: {
		"urn:schemas-upnp-org:device:Basic:1": "/data/Default_Icons/Basic.png",
		"urn:schemas-upnp-org:device:BinaryLight:1": "/data/Default_Icons/Light.png",
		"urn:dial-multiscreen-org:device:dial:1": "/data/Default_Icons/Dial.png",
		"urn:schemas-upnp-org:device:DigitalSecurityCamera:1": "/data/Default_Icons/Camera.png",
		"urn:schemas-upnp-org:device:HVAC_System:1": "/data/Default_Icons/Hvac.png",
		"urn:schemas-upnp-org:device:HVAC_ZoneThermostat:1": "/data/Default_Icons/HvacThermostat.png",
		"urn:schemas-upnp-org:device:InternetGatewayDevice:1": "/data/Default_Icons/Wireless.png",
		"urn:schemas-upnp-org:device:InternetGatewayDevice:2": "/data/Default_Icons/Wireless.png",
		"urn:schemas-upnp-org:device:Light:1": "/data/Default_Icons/Light.png",
		"urn:schemas-upnp-org:device:ManageableDevice:1": "/data/Default_Icons/Managable.png",
		"urn:schemas-upnp-org:device:ManageableDevice:2": "/data/Default_Icons/Managable.png",
		"urn:schemas-upnp-org:device:MediaRenderer:1": "/data/Default_Icons/Render.png",
		"urn:schemas-upnp-org:device:MediaRenderer:2": "/data/Default_Icons/Render.png",
		"urn:schemas-upnp-org:device:MediaRenderer:3": "/data/Default_Icons/Render.png",
		"urn:schemas-upnp-org:device:MediaServer:1": "/data/Default_Icons/Server.png",
		"urn:schemas-upnp-org:device:MediaServer:2": "/data/Default_Icons/Server.png",
		"urn:schemas-upnp-org:device:MediaServer:3": "/data/Default_Icons/Server.png",
		"urn:schemas-upnp-org:device:MediaServer:4": "/data/Default_Icons/Server.png",
		"urn:schemas-upnp-org:device:printer:1": "/data/Default_Icons/Printer.png",
		"urn:schemas-upnp-org:device:RAClient:1": "/data/Default_Icons/RemoteAccessClient.png",
		"urn:schemas-upnp-org:device:RADiscoveryAgent:2": "/data/Default_Icons/RemoteAccessDiscover.png",
		"urn:schemas-upnp-org:device:RAServer:1": "/data/Default_Icons/RemoteAccessServer.png",
		"urn:schemas-upnp-org:device:RAServer:2": "/data/Default_Icons/RemoteAccessServer.png",
		"urn:schemas-upnp-org:device:RemoteUIClientDevice:1": "/data/Default_Icons/RemoteUIClient",
		"urn:schemas-upnp-org:device:RemoteUIServerDevice:1": "/data/Default_Icons/RemoteUIServer.png",
		"upnp:rootdevice": "/data/Default_Icons/Root.png",
		"urn:schemas-upnp-org:device:Scanner:1": "/data/Default_Icons/Scanner.png",
		"urn:schemas-upnp-org:device:SensorManagement:1": "/data/Default_Icons/Sensor.png",
		"urn:schemas-upnp-org:device:SolarProtectionBlind:1": "/data/Default_Icons/Solar.png",
		"urn:schemas-upnp-org:device:TelephonyClient:1": "/data/Default_Icons/TelephonyClient.png",
		"urn:schemas-upnp-org:device:TelephonyClient:2": "/data/Default_Icons/TelephonyClient.png",
		"urn:schemas-upnp-org:device:TelephonyServer:1": "/data/Default_Icons/TelephonyServer.png",
		"urn:schemas-upnp-org:device:TelephonyServer:2": "/data/Default_Icons/TelephonyServer.png",
		"urn:schemas-upnp-org:device:WANDevice:1": "/data/Default_Icons/Wireless.png",
		"urn:schemas-upnp-org:device:WANConnectionDevice:1": "/data/Default_Icons/Wireless.png",
		"urn:schemas-upnp-org:device:WLANAccessPointDevice:1": "/data/Default_Icons/Wireless.png",
		"urn:schemas-wifialliance-org:device:WFADevice:1": "/data/Default_Icons/Wireless.png"
	},
	FontIconClasses: {
		"urn:schemas-upnp-org:service:AddressBook:1": "",
		"urn:schemas-upnp-org:service:AVTransport:1": "glyphicon glyphicon-play",
		"urn:schemas-upnp-org:service:AVTransport:2": "glyphicon glyphicon-play",
		"urn:schemas-upnp-org:service:AVTransport:3": "glyphicon glyphicon-play",
		"urn:schemas-upnp-org:service:BasicManagement:1": "",
		"urn:schemas-upnp-org:service:BasicManagement:2": "",
		"urn:schemas-upnp-org:service:Calendar:1": "glyphicon glyphicon-calendar",
		"urn:schemas-upnp-org:service:CallManagement:1": "glyphicon glyphicon-earphone",
		"urn:schemas-upnp-org:service:CallManagement:2": "glyphicon glyphicon-earphone",
		"urn:schemas-upnp-org:service:ConfigurationManagement:1": "",
		"urn:schemas-upnp-org:service:ConfigurationManagement:2": "",
		"urn:schemas-upnp-org:service:ConnectionManager:1": "",
		"urn:schemas-upnp-org:service:ConnectionManager:2": "",
		"urn:schemas-upnp-org:service:ConnectionManager:3": "",
		"urn:schemas-upnp-org:service:ContentDirectory:1": "fa fa-server",
		"urn:schemas-upnp-org:service:ContentDirectory:2": "fa fa-server",
		"urn:schemas-upnp-org:service:ContentDirectory:3": "fa fa-server",
		"urn:schemas-upnp-org:service:ContentDirectory:4": "fa fa-server",
		"urn:schemas-upnp-org:service:ContentSync:1": "",
		"urn:schemas-upnp-org:service:controlValve:1": "",
		"urn:schemas-upnp-org:service:DataStore:1": "",
		"urn:schemas-upnp-org:service:DeviceProtection:1": "",
		"urn:schemas-upnp-org:service:DeviceSecurity:1": "",
		"urn:schemas-upnp-org:service:DigitalSecurityCameraSettings:1": "",
		"urn:schemas-upnp-org:service:DigitalSecurityCameraStillImage:1": "",
		"urn:schemas-upnp-org:service:DigitalSecurityCameraMotionImage:1": "",
		"urn:schemas-upnp-org:service:DimmingService:1 ": "glyphicon glyphicon-lamp",
		"urn:schemas-upnp-org:service:EnergyManagement:1": "",
		"urn:schemas-upnp-org:service:ExternalActivity:1": "",
		"urn:schemas-upnp-org:service:FanSpeed:1": "",
		"urn:schemas-upnp-org:service:Feeder:1": "",
		"urn:schemas-upnp-org:service:HVAC_UserOperatingMode:1": "",
		"urn:schemas-upnp-org:service:HVAC_FanOperatingMode:1": "",
		"urn:schemas-upnp-org:service:HVAC_SetpointSchedule:1": "",
		"urn:schemas-upnp-org:service:InboundConnectionConfig:1": "",
		"urn:schemas-upnp-org:service:InputConfig:1": "",
		"urn:schemas-upnp-org:service:LinkAuthentication:1": "",
		"urn:schemas-upnp-org:service:Layer3Forwarding:1": "icon-router",
		"urn:schemas-upnp-org:service:LowerPowerDevice:1": "",
		"urn:schemas-upnp-org:service:MediaManagement:1": "",
		"urn:schemas-upnp-org:service:MediaManagement:2": "",
		"urn:schemas-upnp-org:service:Messaging:1": "",
		"urn:schemas-upnp-org:service:Messaging:2": "",
		"urn:schemas-upnp-org:service:Presence:1": "",
		"urn:schemas-upnp-org:service:PrintBasic:1": "",
		"urn:schemas-upnp-org:service:PrintEnhancedLayout:1": "",
		"urn:schemas-upnp-org:service:QosDevice:1": "",
		"urn:schemas-upnp-org:service:QosDevice:2": "",
		"urn:schemas-upnp-org:service:QosDevice:3": "",
		"urn:schemas-upnp-org:service:QosManager:1": "",
		"urn:schemas-upnp-org:service:QosManager:2": "",
		"urn:schemas-upnp-org:service:QosManager:3": "",
		"urn:schemas-upnp-org:service:QosPolicyHolder:1": "",
		"urn:schemas-upnp-org:service:QosPolicyHolder:2": "",
		"urn:schemas-upnp-org:service:QosPolicyHolder:3": "",
		"urn:schemas-upnp-org:service:RadiusClient:1": "",
		"urn:schemas-upnp-org:service:RADASync:1": "",
		"urn:schemas-upnp-org:service:RADASync:2": "",
		"urn:schemas-upnp-org:service:RADAConfig:1": "",
		"urn:schemas-upnp-org:service:RADAConfig:2": "",
		"urn:schemas-upnp-org:service:RATAConfig:1": "",
		"urn:schemas-upnp-org:service:RemoteUIClient:1": "",
		"urn:schemas-upnp-org:service:RemoteUIServer:1": "",
		"urn:schemas-upnp-org:service:RenderingControl:1": "",
		"urn:schemas-upnp-org:service:Scan:1": "",
		"urn:schemas-upnp-org:service:ScheduledRecording:1": "",
		"urn:schemas-upnp-org:service:ScheduledRecording:2": "",
		"urn:schemas-upnp-org:service:SecurityConsole:1": "",
		"urn:schemas-upnp-org:service:SensorTransportGeneric:1": "",
		"urn:schemas-upnp-org:service:SoftwareManagement:1": "",
		"urn:schemas-upnp-org:service:SoftwareManagement:2": "",
		"urn:schemas-upnp-org:service:SwitchPower:1 ": "",
		"urn:schemas-upnp-org:service:TemperatureSensor:1": "",
		"urn:schmeas-upnp-org:service:TemperatureSetpoint:1": "",
		"urn:schemas-upnp-org:service:TwoWayMotionMotor:1": "",
		"urn:schemas-upnp-org:device:WANConnectionDevice:1": "icon-router",
		"urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1": "icon-router",
		"urn:schemas-upnp-org:service:WANIPConnection:1": "icon-router",
		"urn:schemas-upnp-org:service:WANPPPConnection:1": "icon-router",
		"urn:schemas-upnp-org:service:WLANConfiguration:1": "icon-router",
		"urn:Microsoft Windows Peer Name Resolution Protocol:v4:IPV6:LinkLocal": "",
		"urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1": "",
		"urn:samsung.com:service:MultiScreenService:1": "",
		"urn:dial-multiscreen-org:service:dial:1": "",
		"urn:schemas-sony-com:service:IRCC:1": "",
		"urn:schemas-sony-com:service:Party:1": "",
		"urn:schemas-sony-com:service:X_CIS:1": "",
		"urn:upnp-org:serviceId:WANCommonIFC1": "icon-router",
		"urn:schemas-wifialliance-org:service:WFAWLANConfig:1": "icon-router",
		"audio": "glyphicon glyphicon-headphones",
		"video": "glyphicon glyphicon-film",
		"image": "glyphicon glyphicon-picture",
		"mirror":"glyphicon glyphicon-blackboard"
	}
};